
logging:
  file: ${logging.path}/fileserver.log

spring:
  jmx:
    # this gives Hikari Datasource an unique name, so Fileserver and UI may run parallel in Tomcat
    default-domain: datasource-fileserver

# This is used only when started from the spring-boot maven plugin, irrelevant to deployment in a servlet container
server:
  port: 8980
