version: "2.2"

services:

  mediaserver:
    image: tubub/kitodo-mediaserver:1.0.0
    ports:
      - 8080:8080
    volumes:
      # config directory
      - /usr/local/kitodo-mediaserver/config:/usr/local/kitodo-mediaserver/config
      # data directorys
      - /var/local/kitodo-mediaserver/cache:/var/local/kitodo-mediaserver/cache
      - /var/local/kitodo-mediaserver/files:/var/local/kitodo-mediaserver/files
      - /var/local/kitodo-mediaserver/hotfolder:/var/local/kitodo-mediaserver/hotfolder
      - /var/local/kitodo-mediaserver/importing:/var/local/kitodo-mediaserver/importing
      - /var/local/kitodo-mediaserver/import_error:/var/local/kitodo-mediaserver/import_error
      # logs
      - /var/local/kitodo-mediaserver/logs:/var/local/kitodo-mediaserver/logs
    depends_on:
      database:
        condition: service_healthy
#    environment:
#      - MS_UPDATE_DB=
#      - MS_FILESERVER_PATH=
#      - MS_UI_PATH=
#      - MS_PROXY_NAME=
#      - MS_PROXY_PORT=

  database:
    image: mysql:5.7
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      # MySQL database files
      - /var/local/kitodo-mediaserver/database:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=mediaserver
      - MYSQL_USER=kitodo
      - MYSQL_PASSWORD=kitodo
      - MYSQL_ROOT_PASSWORD=kitodo

  # optional: phpmyadmin to manage database
#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin
#    depends_on:
#      - database
#    environment:
#      PMA_HOST: database
#      PMA_PORT: 3306
#    ports:
#      - '8081:80'
