################################################################
#
# This is a file for local configurations of Kitodo Mediaserver
#
# Entries in this file override settings in default.yml
#
#################################################################

