################################################################
#
# This is a file for local configurations of Kitodo Mediaserver
#
# Entries in this file override settings in default.yml
#
#################################################################

logging:
  path: /srv/kitodo/mediaserver/logs/

fileserver:
  rootUrl: http://localhost:8980/files/
  caching: true
  cachePath: /srv/kitodo/mediaserver/cache/

mets:
  originalFileGrpSuffix: PRESENTATION

indexing:
  indexScriptUrl: http://localhost/kitodo-indextest.php

importer:
  hotfolderPath: /srv/kitodo/mediaserver/hotfolder/
  importingFolderPath: /srv/kitodo/mediaserver/importing/
  tempWorkFolderPath: /srv/kitodo/mediaserver/import_temp/
  errorFolderPath: /srv/kitodo/mediaserver/import_error/
  workFilesPath: /srv/kitodo/mediaserver/files/
  cron: 0 0 * * * *

  validationFileGrps:
  - PRESENTATION
  - FULLTEXT

  watermark:
    enabled: true
    minSize: 600
    renderMode: text
    gravity: "southwest"
    offsetX: 25
    offsetY: 0
    textMode:
      content: "Example Text"
      font: "Arial"
      colorRGB: "34,65,255"
      size: 16
    imageMode:
      path: /srv/kitodo/assets/watermark.png
      opacity: 75
    extendCanvas:
      enabled: true
      backgroundColorRGB: "0,0,0"
      addX: 0
      addY: 25
