################################################################
#
# This is a file for local configurations of Kitodo Mediaserver
#
# Entries in this file override settings in default.yml
#
#################################################################

fileserver:
  rootUrl: http://localhost:8980/files/
  caching: true
  cachePath: /srv/kitodo-mediaserver/data/cache/

mets:
  originalFileGrpSuffix: PRESENTATION

importer:
  hotfolderPath: /srv/kitodo-mediaserver/data/hotfolder/
  importingFolderPath: /srv/kitodo-mediaserver/data/importing/
  errorFolderPath: /srv/kitodo-mediaserver/data/import_error/
